components/TForm.vue, components/TInput/TInputDateTime.vue, package.json, pages/components/date.vue, pages/events/_id/edit.vue, utils.js, yarn.lock
Old DateTimePicker got frozen in Safari after setting time.
There was a problem with recursive field updates and conversion to date.
=> fix: event editor in safari

README.md
- add prerequisites with specific versions
- add workaround for Node Sass
=> docs: setup

pages/events/_id/dashboard.vue
Fixed event dashboard sending email.
=> fix event dashboard sending email

nuxt.config.js
For every change hot-reload takes around 20 sec. But doing so makes it 2 sec.
Solution by @booleanrecep 
Demo: https://wedance-razbakov.netlify.app/
Related #38
Related issues:
- https://github.com/vuejs/vue-loader/issues/1426
=> skip prettier in vue

components/TItemComments.vue, components/TItemToolbar.vue, locales/en.yml, pages/feed.vue, use/posts.js
Resolves #79 
Demo Link: https://wedance-stefanacef.netlify.app/feed/
=> i18n: feed #79

locales/de.yml, locales/en.yml, locales/es.yml, locales/fr.yml, locales/he.yml, locales/it.yml, locales/pl.yml, locales/pt.yml, locales/ro.yml, locales/ru.yml, locales/sr.yml, locales/tr.yml, pages/events/index.vue
Resolves #78  
Demo Link: https://wedance-amanuela97.netlify.app/events/
=> i18n: Calendar

components/Card/TCardEvent.vue, components/TEventText.vue, components/TInput/TInputVenue.vue, pages/community.vue, pages/events/_id/dashboard.vue, pages/events/_id/edit.vue, pages/events/_id/index.vue, pages/events/index.vue, pages/feed.vue, pages/posts/_id/edit.vue, pages/register.vue, pages/settings.vue, use/accounts.js, use/events.js, use/forms.js, use/i18n.js, use/posts.js, use/profiles.js, use/venues.js
Refactored `~/use/*.js` libraries to be used in setup context.
Now it's possible to use translation function `t()` inside of this libraries like this:
```js
import { useI18n } from '~/use/i18n'
const { t } = useI18n()
```
Closes #92
=> chore: i18n form fields

components/MainNavigation.vue, layouts/popup.vue, locales/de.yml, locales/en.yml, locales/es.yml, locales/fr.yml, locales/he.yml, locales/it.yml, locales/pl.yml, locales/pt.yml, locales/ro.yml, locales/ru.yml, locales/sr.yml, locales/tr.yml, pages/index.vue, pages/settings.vue
Shall we switch to this format of i18n files?
=> style: i18n

locales/en.yml, pages/chat/_slug.vue, pages/chat/index.vue
Chat is ready for localisation.
Demo:
- https://wedance-stefanacef.netlify.app/chat/ 
- https://wedance-stefanacef.netlify.app/chat/Stefana
Closes #105
=> i18n: Chat

locales/en.yml, pages/events/_id/index.vue
Demo: https://wedance-amanuela97.netlify.app/events/4GxMq5D1ZcQXlN4DfKHM
Closes #72
=> i18n: Event view

components/TEventText.vue, pages/events/index.vue
=> fix calendar type filter

locales/en.yml, pages/index.vue
* Localization added in Home page
* Keys for localization created in en.yml file
https://nelson-wedance.netlify.app/
Closes #80
=> i18n: Home

components/Card/TCardEvent.vue, components/TAvatar.vue, components/TButton.vue, components/TEventText.vue, components/TFooter.vue, components/TPost.vue, components/TProfile.vue, components/TProfileCard3.vue, components/TStyles.vue, components/global/WProfile.vue, layouts/public.vue, pages/chat/_slug.vue, pages/chat/index.vue, pages/community.vue, pages/dance/_slug.vue, pages/dance/index.vue, pages/events/index.vue, pages/index.vue, pages/lists/index.vue, pages/nopassword.vue, pages/register.vue, pages/search.vue, pages/settings.vue, pages/signin.vue
=> speedup page loading

components/TFooter.vue, package.json
=> feat: show version in footer

components/MainNavigation.vue, components/TButton.vue, components/TEventText.vue, components/TInput/TInputButtons.vue, locales/en.yml, nuxt.config.js, pages/cities.vue, pages/community.vue, pages/events/_id/index.vue, pages/events/index.vue, pages/feed.vue, use/cities.js, use/events.js, use/styles.js
Demo: https://wedance-razbakov.netlify.app/anywhere/travel/any-dance/any-level
Closes #115
=> feat: calendar navigation

components/Actions/TReactions.vue, components/Actions/TStars.vue, components/TButton.vue, components/TPost.vue, layouts/default.vue, locales/en.yml
Demo: https://wedance-stefanacef.netlify.app/nopassword/
Closes #73
=> i18n: Auth

locales/en.yml, pages/events/_id/dashboard.vue
How to access Event Dashboard:
- Go to Calendar in Main Navigation
- Create event - click "plus" icon in the header
- Fill the fields and click save
- On the event page click more (three dots in the header) and click Dashboard
Closes #76
=> i18n: Event Dashboard

functions/src/index.ts, functions/src/lib/algolia.ts
TInputProfile should search profiles by WeDance username, name, instagram and facebook. 
This component is used now in Organiser and Artists fields in Event Editor.
=> api: search by instagram and facebook

components/MainNavigation.vue, components/TCardActions.vue, components/TItemToolbar.vue, components/TPost.vue, components/TPostList.vue, components/TProfile.vue, components/TProfileDetails.vue, locales/en.yml
- inspect source code
- https://wedance-amanuela97.netlify.app/amanuel
closes #74
=> i18n: profile #74

components/TPreview.vue, components/TProfile.vue, package.json, pages/_slug/index.vue, pages/dance/_slug.vue, pages/dance/index.vue, pages/nopassword.vue, tailwind.config.js, yarn.lock
I have installed typography plugin and added it in tailwind.config.js file.
And you can test it on the profile page of a user, it should be visible right after the 'Welcome to WeDance!' line.
You can test it locally by switching to issue/127 branch and then yarn dev.
Deploy preview: https://6203ab6b4f017c00087232ed--wedance-harshbrahmxatriya.netlify.app/
=> chore: add tailwind typography plugin #127

components/TEventList.vue, components/TProfile.vue, pages/_slug/embed.vue
As an Organiser I want to copy embed code so that I can include calendar on my website
- copy calendar as text for announcements in chat
- copy iframe code to include on website
=> Embed Calendar as iFrame

pages/events/_id/copy.vue
fix typo in the last commit, which break object and event wasn't able to copy
=> fix copy event

components/TProfile.vue, components/global/WTeaser.vue, locales/en.yml
Every city page now have an "Ask Locals" section that leads to Telegram chat
=> Ask locals

components/TPreview.vue, package.json, yarn.lock
Text @alexrazbakovwill be rendered as a link: [@alexrazbakov](https://wedance.vip/alexrazbakov) in TPreview
Add 'markdown-it-mentions' plugin.
Closes #322
=> TPreview shows @mention as link to profile

components/TCalendar.vue, components/TCommunity.vue, pages/nopassword.vue, pages/signin.vue, pages/signout.vue
=> fix: login ends up in 404

components/TReviewForm.vue
Successfully improved the UX bug and toggle the visibility of that form. You can checkout the attached video for more info related to the output @razbakov 
https://github.com/user-attachments/assets/72c21b55-196d-4851-9a41-1ba24bf426d4
=> This fixed a UX bug related to hide Form issue

components/TReviewForm.vue
=> lint error fix

nuxt.config.js, pages/events/_id/index.vue, plugins/stripe.js, use/events.js
As an event organizer, I want to integrate Stripe Pricing Table into my event page so that attendees can purchase tickets directly on the site without being redirected to external pages.
Closes #374
This PR adds the ability to embed Stripe Pricing Tables in event pages, allowing organizers to sell tickets and collect payments directly within the site. This creates a seamless ticket purchasing experience for event attendees.
The implementation enables two possible scenarios for buying tickets:
1. If the "Link to get tickets" field is filled, clicking the "Buy Ticket" button will navigate to the external URL.
2. If the "Link to get tickets" field is empty and a valid Stripe Pricing Table code is provided, clicking the "Buy Ticket" button will open a popup with the Stripe Pricing Table …
=> Add Stripe Pricing Table integration for event ticket sales
